FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel

RUN apt-get update \ 
    && apt-get upgrade -y \
    && python -m pip install --upgrade pip

ADD requirements.txt ./
RUN pip install torch-scatter\
                torch-sparse\
                torch-cluster\
                torch-spline-conv\
                torch-geometric \
                -f https://data.pyg.org/whl/torch-1.12.0+cu113.html
               
WORKDIR /examples/graphproppred/mol